import Link from 'next/link';
import './globals.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='bg-black-100'>
        <div>
          <header className='bg-blue-600 text-white p-4 shadow-lg'>
            <h1 className='text-3xl font-bold'>Main Website Header</h1>
            {/* Navigation Bar */}
            <nav className='mt-4'>
              <ul className='flex justify-center space-x-8'>
                <li>
                  <Link href='/' legacyBehavior>
                    <a className='text-white hover:underline'>Home</a>
                  </Link>
                </li>
                <li>
                  <Link href='/profile' legacyBehavior>
                    <a className='text-white hover:underline'>Profile</a>
                  </Link>
                </li>

                <li>
                  <Link href='/blog' legacyBehavior>
                    <a className='text-white hover:underline'>Blog</a>
                  </Link>
                </li>
                <li>
                  <Link href='/products' legacyBehavior>
                    <a className='text-white hover:underline'>Products</a>
                  </Link>
                </li>
              </ul>
            </nav>
          </header>
          <main className='flex-grow container mx-auto p-6'>{children}</main>
        </div>
      </body>
    </html>
  );
}
